### ISSUE TITLE
启动遇到问题

### ISSUE THREAD

**Issue by 52Lau** [BruceDone/clock#1]
"""
直接使用
下载git上的release列表，根据系统下载相应的二进制文件，使用命令

./clock -c ./config/dev.yaml
"""

![image](https://user-images.githubusercontent.com/37538641/87642955-d1ec0700-c77c-11ea-81b9-8ea8bd5eb491.png)

**Comment by BruceDone** [comment]
@52Lau 启动文件在代码里面，参考一下：https://github.com/BruceDone/clock/blob/master/config/dev.yaml
