### ISSUE TITLE
内存占用问题

### ISSUE THREAD

**Issue by CLannadZSY** [BruceDone/clock#10]
![QQ图片20200817095931](https://user-images.githubusercontent.com/38000492/90350726-917bf380-e070-11ea-86a5-a05b66078200.png)

占用了 `72.8%`, `22.7g` 的内存, 你不会是把所有日志都缓存到内存中了吧? 或者说是我的什么操作, 设置不对?

**Comment by BruceDone** [comment]
@CLannadZSY 日志是存在持久化的数据库里面(sqlite 或者你配置的其它数据库) ，是你当前的命令做了某些大内存的操作吗？我本地clock已经运行快半年了，内存占用不到10M
