### ISSUE TITLE
下载linux的release版本运行失败

### ISSUE THREAD

**Issue by 5uw1st** [BruceDone/clock#2]
**[root@node2 clock-test]# ll**
total 20480
drwxr-xr-x 12 root root      246 Jul 17 17:30 clock
-rwxr-xr-x  1 root root 20967655 Jul 17 17:25 clock-linux-64
**[root@node2 clock-test]# ./clock-linux-64 -c clock/config/**
config.go  dev.yaml   
**[root@node2 clock-test]# ./clock-linux-64 -c clock/config/dev.yaml** 
INFO[0000] [config] run the env with:clock/config/dev.yaml 
INFO[0000] [param] load user                            
INFO[0000] [param] load DbConn                          
FATA[0000] Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub 
**[root@node2 clock-test]# uname -a**
Linux node2.k8s.litb.com 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@node2 clock-test]#

**Comment by BruceDone** [comment]
多谢你的issue，正在重新编译之中

**Comment by BruceDone** [comment]
@5uw1st 已经重新编译上传了，可以试试
