### ISSUE TITLE
how to run test case

### ISSUE THREAD

**Issue by ronething** [BruceDone/clock#5]
- 你好，跑了 storage 下面的 model_test/TestFindOne 出现以下错误，应该是 config 配置没有载入，想请问如何进行单元测试

![image](https://user-images.githubusercontent.com/28869910/87936661-cd4d8880-cac5-11ea-9223-a61c08f4aeca.png)

**Comment by BruceDone** [comment]
你好，需要在run test case 时候需要载入配置，这个我来完善一下，多谢你的issue
