### ISSUE TITLE
linux 上运行失败

### ISSUE THREAD

**Issue by CLannadZSY** [BruceDone/clock#8]
无论是`zsy`还是`root` 用户都提示没有权限, 截图如下

![image](https://user-images.githubusercontent.com/38000492/88997301-f53cb780-d321-11ea-9a6f-4b6256bd70ce.png)
![image](https://user-images.githubusercontent.com/38000492/88997325-008fe300-d322-11ea-9bba-5fb70cc569a6.png)

**Comment by BruceDone** [comment]
@CLannadZSY 当前用户下你只有read write 权限 ，你新增可以执行权限，chmod +x clock-linux-64
